### ISSUE TITLE
RELEASE of rsa-aes128gcm  Encryption

### ISSUE THREAD

**Issue by ghul0** [erasmus-without-paper/ewp-specs-sec-reqencr-rsa-aes128cbc#1]
Are there any plans to release rsa-aes128gcm request encryption method?
it is in Version 0.4.0 - REVIEW RECOMMENDED for a while. 
is there any node who using it or planning to use it?

**Comment by janinamincer-daszkiewicz** [comment]
We do not know about any such node so just wait what will happen. On the one hand once we have been asked to specify it, on the other at the moment nobody seems to be interested. Hard to say what the future will show.
